//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CartItem
    {
        public int CartItem { get; set; }
        public int CartId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal PriceTotal { get; set; }
        public decimal TemPrice { get; set; }
        public int ProductDetailId { get; set; }
    
        public virtual tb_Cart tb_Cart { get; set; }
        public virtual tb_ProductDetail tb_ProductDetail { get; set; }
    }
}
