//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ImportWarehouse
    {
        public int ImportWarehouseId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifeby { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public Nullable<int> ProductDetailId { get; set; }
        public Nullable<int> QuanTity { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual tb_ProductDetail tb_ProductDetail { get; set; }
        public virtual tb_Staff tb_Staff { get; set; }
        public virtual tb_Warehouse tb_Warehouse { get; set; }
    }
}
