//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ProductDetail()
        {
            this.tb_CartItem = new HashSet<tb_CartItem>();
            this.tb_ImportWarehouse = new HashSet<tb_ImportWarehouse>();
            this.tb_OrderDetail = new HashSet<tb_OrderDetail>();
            this.tb_ProductDetailImage = new HashSet<tb_ProductDetailImage>();
            this.tb_Review = new HashSet<tb_Review>();
        }
    
        public int ProductDetailId { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<decimal> OrigianlPrice { get; set; }
        public Nullable<bool> TypeProduct { get; set; }
        public string Image { get; set; }
        public Nullable<int> DungLuongPin { get; set; }
        public Nullable<int> Ram { get; set; }
        public Nullable<int> DungLuong { get; set; }
        public Nullable<int> ProductsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CartItem> tb_CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ImportWarehouse> tb_ImportWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderDetail> tb_OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetailImage> tb_ProductDetailImage { get; set; }
        public virtual tb_Products tb_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Review> tb_Review { get; set; }
    }
}
