//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ReviewDetail
    {
        public int ReviewDetailId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifeby { get; set; }
        public string Content { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public Nullable<int> IdKhachHang { get; set; }
    
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_Review tb_Review { get; set; }
    }
}
