//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Role
    {
        public int NhanVienId { get; set; }
        public int IdChucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tb_Function tb_Function { get; set; }
        public virtual tb_Staff tb_Staff { get; set; }
    }
}
