//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Staff()
        {
            this.tb_ExportWareHouse = new HashSet<tb_ExportWareHouse>();
            this.tb_ImportWarehouse = new HashSet<tb_ImportWarehouse>();
            this.tb_Role = new HashSet<tb_Role>();
        }
    
        public int NhanVienId { get; set; }
        public string MSNV { get; set; }
        public string SDT { get; set; }
        public string TenNhanVien { get; set; }
        public string CCCD { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public System.DateTime Birthday { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public decimal Luong { get; set; }
        public string GioiTinh { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> Clock { get; set; }
        public Nullable<int> IdChucNang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExportWareHouse> tb_ExportWareHouse { get; set; }
        public virtual tb_Function tb_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ImportWarehouse> tb_ImportWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Role> tb_Role { get; set; }
        public virtual tb_StaffImage tb_StaffImage { get; set; }
    }
}
